/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMPO_H_RPCGEN
#define _TEMPO_H_RPCGEN

#include <rpc/rpc.h>

//#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct timeval_ {
	long tv_sec;
	long tv_usec;
};
typedef struct timeval_ timeval_;

#define TEMPOPROG 0x12345
#define TEMPOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TEMPO 1
extern  enum clnt_stat tempo_1(void *, timeval_ *, CLIENT *);
extern  bool_t tempo_1_svc(void *, timeval_ *, struct svc_req *);
extern int tempoprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TEMPO 1
extern  enum clnt_stat tempo_1();
extern  bool_t tempo_1_svc();
extern int tempoprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_timeval_ (XDR *, timeval_*);

#else /* K&R C */
extern bool_t xdr_timeval_ ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMPO_H_RPCGEN */
