/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "tempo.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
tempo_1(void *argp, timeval_ *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, TEMPO,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_timeval_, (caddr_t) clnt_res,
		TIMEOUT));
}
