/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQUARE_H_RPCGEN
#define _SQUARE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct square_in {
	long arg;
};
typedef struct square_in square_in;

struct square_out {
	long res;
};
typedef struct square_out square_out;

struct req_out {
	char flag;
	int a_int;
	int other_int;
};
typedef struct req_out req_out;

struct req_in {
	char flag;
	int a_int;
	int other_int;
};
typedef struct req_in req_in;

#define SQUARE_PROG 0x12340000
#define SQUARE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SQUAREPROC 1
extern  enum clnt_stat squareproc_1(square_in *, square_out *, CLIENT *);
extern  bool_t squareproc_1_svc(square_in *, square_out *, struct svc_req *);
#define REQPROC 2
extern  enum clnt_stat reqproc_1(req_in *, req_out *, CLIENT *);
extern  bool_t reqproc_1_svc(req_in *, req_out *, struct svc_req *);
extern int square_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SQUAREPROC 1
extern  enum clnt_stat squareproc_1();
extern  bool_t squareproc_1_svc();
#define REQPROC 2
extern  enum clnt_stat reqproc_1();
extern  bool_t reqproc_1_svc();
extern int square_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_square_in (XDR *, square_in*);
extern  bool_t xdr_square_out (XDR *, square_out*);
extern  bool_t xdr_req_out (XDR *, req_out*);
extern  bool_t xdr_req_in (XDR *, req_in*);

#else /* K&R C */
extern bool_t xdr_square_in ();
extern bool_t xdr_square_out ();
extern bool_t xdr_req_out ();
extern bool_t xdr_req_in ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQUARE_H_RPCGEN */
